### ISSUE TITLE
Accept parameter and Kombu<3.0.0

### ISSUE THREAD

**Issue by skudriashev** [ceelian/callme#21]
After adding the 'accept' parameter to the consumer - code stopped to work on Kombu<3.0.0 with
(TypeError: __init__() got an unexpected keyword argument 'accept').
Shell you revert this, since we already added 'kombu>=1.2.1,<3.0.0' in the install_requires?
